import turtle
t= turtle.Turtle()
turtle.title("Drawing rectangle with python")
t.begin_fill()
t.fd(150)
t.rt(90)
t.fd(100)
t.rt(90)
t.fd(150)
t.rt(90)
t.fd(100)
t.rt(90)
t.end_fill()
turtle.mainloop()
