import turtle
t= turtle.Turtle()
turtle.title("Drawing square with python")
t.speed(2)
t.begin_fill()
t.fd(100)
t.rt(90)
t.fd(100)
t.rt(90)
t.fd(100)
t.rt(90)
t.fd(100)
t.rt(90)
t.end_fill()
turtle.mainloop()
